% (Written by Felipe Espic, 2016)

% INSTRUCTIONS:
% This script generates waveforms from STRAIGHT-type acoustic 
% parameters (only lf0 and mgc, no bap needed!).
% You can use other vocoders for feature extraction as well, e.g., WORLD.
% or can be generated by an acoustic model, e.g. Merlin toolkit.
% See the INPUT section for more details on the input parameters.
% For this demo, we provide male and female voices as examples, but you can
% use any acoustic parameters you want.
% We encourage you to compare the results with other waveform generators (e.g., STRAIGHT, WORLD) 

%%
clear;
clc;

addpath(genpath('../src'))

%% INPUT

fs    = 48000; % Sample frequency
nMGCs = 60;    % Number of Mel-cepstral coefiicients. 
nfft  = 4096;  % FFT length.

% Female:
%{
lf0FilePath = './data_demo/params/4022_1.lf0';
mgcFilePath = './data_demo/params/4022_1.mgc';
%}

% Male:
%%{
lf0FilePath = './data_demo/params/hvd_661.lf0';
mgcFilePath = './data_demo/params/hvd_661.mgc';
%}

out_wav_dir = './data_demo/wavs_syn';

%% BODY

% Read acoustic parameters:
vf0 = ReadLf0File(lf0FilePath);   
mSp = ReadMgcFile(mgcFilePath, nMGCs, nfft); 

% Synthesis:
vSynSig = WavGenSR(vf0, mSp, fs);

% Save:
mkdir(out_wav_dir)
[~, fname] =  fileparts(lf0FilePath);
audiowrite([out_wav_dir '/' fname '.wav'], vSynSig / max(abs(vSynSig)), fs);
